# Generated by Django 3.2.5 on 2021-07-31 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('zip_code', models.CharField(default='', max_length=12, verbose_name='Postal Code')),
                ('city', models.CharField(default='', max_length=100)),
                ('street', models.CharField(default='', max_length=100)),
                ('number1', models.IntegerField(default=0)),
                ('number2', models.IntegerField(blank=True, null=True)),
                ('date_of_modification', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
