# Generated by Django 3.2.4 on 2021-06-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='author',
            new_name='owner',
        ),
    ]
