# Generated by Django 3.2.4 on 2021-07-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_rename_author_contact_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default='CITY NAME', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='number1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='contact',
            name='number2',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(default='STREET NAME', max_length=100),
        ),
    ]
