# Generated by Django 3.2.4 on 2021-07-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0003_auto_20210704_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='voivodeship',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='zip_code',
            field=models.CharField(default='', max_length=12, verbose_name='ZIP/Postal Code'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number2',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
    ]
