# Generated by Django 3.2.4 on 2021-07-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0005_alter_contact_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='voivodeship',
        ),
        migrations.AlterField(
            model_name='contact',
            name='number1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
